### PR TITLE
Optimize PLONK

### PR DESCRIPTION
**Pull request by kwanCCC**

### CODE REVIEW

**Comment by kwanCCC** [comment]
Some code about GPU-kit was copied from filecoin which had been optimized by @keyvank keyvank 's help.

Working In Progress !

**Comment by kwanCCC** [comment]
There are some temporary version association. When the first stage was stable, there would be none tmp dependencies.  
Leave a record here.
* https://github.com/zeeka-network/bls12_381/tree/feature/base090
* https://github.com/zeeka-network/jubjub/blob/feature/base11/Cargo.toml
* https://github.com/zeeka-network/ec-gpu/tree/feature/base-c

**Comment by kwanCCC** [comment]
```
--------------------------------------
Testing FFT3 for 16384 elements...
GPU took 26ms.
CPU (32 cores) took 121ms.
Speedup: x4.6538463
--------------------------------------
Testing FFT3 for 32768 elements...
GPU took 25ms.
CPU (32 cores) took 200ms.
Speedup: x8
--------------------------------------
Testing FFT3 for 65536 elements...
GPU took 26ms.
CPU (32 cores) took 358ms.
Speedup: x13.769231
--------------------------------------
Testing FFT3 for 131072 elements...
GPU took 30ms.
CPU (32 cores) took 656ms.
Speedup: x21.866667
--------------------------------------
Testing FFT3 for 262144 elements...
GPU took 36ms.
CPU (32 cores) took 1175ms.
Speedup: x32.63889
--------------------------------------
Testing FFT3 for 524288 elements...
GPU took 39ms.
CPU (32 cores) took 2048ms.
Speedup: x52.51282
--------------------------------------
Testing FFT3 for 1048576 elements...
GPU took 50ms.
CPU (32 cores) took 4369ms.
Speedup: x87.38
--------------------------------------
```

**Comment by keyvank** [comment]
@kwanCCC Wow this is nice! What is the impact on total proving time?

**Comment by kwanCCC** [comment]
@keyvank, I will provide a summary about AB test later.

**Comment by kwanCCC** [comment]
I had do a simple ABTest with 2*GPU
```
524288 gates

Zeeka-Plonk
Compile circuit 115.053416599s
Prove 650.780106183s
Verify 134.439076ms

Dusk-Plonk
Compile circuit  451.612713242s
Prove 1093.355182688s
Verify 137.196371ms
```
It seems replacing FFT with _2*GPU_ version improves the performance by _2x_ and so on it would be _4x_ if there is _4*GPU_. @keyvank

**Comment by keyvank** [comment]
@kwanCCC How big was your circuit? (How many constraints?)

**Comment by kwanCCC** [comment]
@keyvank , 524288 gates

**Comment by keyvank** [comment]
@kwanCCC Do you think this could potentially as fast as bellman? (In terms of proving time per constraint)

**Comment by kwanCCC** [comment]
In my understanding, dusk's implementation is more closer to the paper. For example, the circuit which in Dusk structural supports an definition that the input in gate can be regarded as public input. Also the Dusk do some extra works for usage. It define `q4` in the polynomial which the constraint is actually `q_m · a · b  + q_l · a + q_r · b + q_o · o + q_4 · d + q_c + PI = 0`. so it does more calculations than bellman. So If dusk and bell compare in performance, there is a small chance of winning. @keyvank

**Comment by kwanCCC** [comment]
In terms of my current experience
```
constraint in bell
q_m · a · b + q_l · a + q_r · b + q_o · o + q_c  = 0
```
```
constraint in dusk
q_m · a · b + q_l · a + q_r · b + q_o · o + q_4 · d + q_c + PI = 0
```
So I think the selection result is affected by the structure of the circuit diagram. If there is more `multiplication gate` or `a + b + d`, the dusk maybe better. But I don't know yet about these things how affect the performance of bellman.

**Pull request merged**
